### PR TITLE
feat(c): Add growing queue functionality

### PR DESCRIPTION
**Pull request by SanjoDeundiak**
### Proposed Changes
- Added ability to grow queue

### TODO
- Resolve memory free with 0 buff_size
- Resolve automatically grow on enqueue if needed

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@SanjoDeundiak thank you for sending this PR ❤️ 
Our commit message convention requires that the messages our in lower case, could you amend the commit and change `Add` to `add`

**Comment by SanjoDeundiak** [comment]
@mrinalwadhwa thank you for such a nice feedback! I've fixed the commit message.

**Comment by mrinalwadhwa** [comment]
@SanjoDeundiak could you resolve conflict with the latest changes in develop. Thank you.

**Comment by SanjoDeundiak** [comment]
@mrinalwadhwa check it please

**Comment by mrinalwadhwa** [comment]
@SanjoDeundiak looks good, I'll confirm that it builds and then merge shortly. 👍

**Pull request merged**
