### PR TITLE
native functions

### PR DESCRIPTION
**Pull request by mrinalwadhwa**
- build(rust): vault crate with ffi feature on by default
- feat(elixir): remove key exchange native functions
- style(elixir): fix unaliased nested modules and format
- build(elixir): compile native functions based on operating system
- build(elixir): ockam_vault_software with native functions
- build: make elixir gradle depend on rust gradle

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
This PR sets a gradle dependency to build Rust before Elixir and uses that build the Elixir native functions.

Fixes
https://github.com/ockam-network/ockam/issues/534
https://github.com/ockam-network/ockam/issues/530

@SanjoDeundiak
I removed the key exchange NIF functions for now, and saved the code in this branch
https://github.com/ockam-network/ockam/tree/mrinal/save/key-exchange-nif
We can add it back when we've figured out how to make the Rust+Elixir key exchange work. 

@mikelodder7 note that this sets the vault crate to build by default with FFI feature on, let me know if you see a problem with that.

**Comment by mikelodder7** [comment]
The problem with ffi on by default is that it’s not needed if you are pure rust or using this as a crate. It can still be turned off but requires rust developers to do more work

**Comment by mrinalwadhwa** [comment]
Logging https://github.com/ockam-network/ockam/issues/542 and https://github.com/ockam-network/ockam/issues/543 that we should discuss later.

**Comment by nilslice** [comment]
> @mikelodder7 note that this sets the vault crate to build by default with FFI feature on, let me know if you see a problem with that.

if it's just something we want to build on CI for testing purposes, the feature can be passed to `cargo build --features ffi` 

not sure if that addresses this particular issue...

**Comment by mrinalwadhwa** [comment]
let's discuss that later on the above two issues.

**Review by nilslice — APPROVED** [review]

**Review by nilslice — APPROVED** [review]

**Comment by nilslice** [comment]
this was a test to try an alternative rebase+merge flow. closing.

**Pull request merged**
