### PR TITLE
ci: cache gradle

### PR DESCRIPTION
**Pull request by metaclips**
### Proposed Changes
Cache Gradle download demo action https://github.com/ockam-network/ockam/runs/3202058495
closes https://github.com/ockam-network/ockam/issues/1526

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
I hadn't realized that commit lint allows multiple scopes - could you change the commit message to just:
```
ci: cache gradle
```

**Comment by metaclips** [comment]
> I hadn't realized that commit lint allows multiple scopes - could you change the commit message to just:
> 
> ```
> ci: cache gradle
> ```

Fixed.

**Comment by metaclips** [comment]
> I hadn't realized that commit lint allows multiple scopes - could you change the commit message to just:
> 
> ```
> ci: cache gradle
> ```

@mrinalwadhwa we shouldn't allow multiple scopes in commit?

**Comment by jared-s** [comment]
Merged as https://github.com/ockam-network/ockam/pull/1677

**Pull request closed without merging**
