### PR TITLE
improve documentation

### PR DESCRIPTION
**Pull request by mrinalwadhwa**
WORK IN PROGRESS

### CODE REVIEW

**Review by mattgreg — DISMISSED** [review]
My opinion is that we don't need to let the links block this PR. I'll come back to this with better links once we push the new `/learn` pages on the website.

**Review by nilslice — APPROVED** [review]
looks great!

**Comment by mrinalwadhwa** [comment]
@nilslice I'll squash, then we can merge.

**Comment by mrinalwadhwa** [comment]
@nilslice please merge when the build passes.

**Review by nilslice — APPROVED** [review]

**Pull request merged**
