### PR TITLE
Worker trait definitions

### PR DESCRIPTION
**Pull request by jared-s**
# Worker Traits

Defines:
1. ockam crate
2. Worker trait
3. ClosureWorker implementation
4. minimal WorkerContext

### CODE REVIEW

**Review by robinbudd — APPROVED** [review]

**Comment by jared-s** [comment]
@mrinalwadhwa ready for you to have a look.

**Review by mrinalwadhwa — CHANGES_REQUESTED** [review]
The content looks ready to merge:

A couple of quick changes to the commits:

- f50e0c8bcf7901a5fd947b027f5b5eeb5cafc075 is not signed
- 314c68fe6c083de5c67475f9cd0e64b12cd50fdf a better commit message would be something like:

```
feat(rust): worker module

Define
1. Worker trait
2. ClosureWorker
3. Minimal WorkerContext
```

**Comment by jared-s** [comment]
> The content looks ready to merge:
> 
> A couple of quick changes to the commits:
> 
>     * [f50e0c8](https://github.com/ockam-network/ockam/commit/f50e0c8bcf7901a5fd947b027f5b5eeb5cafc075) is not signed
> 
>     * [314c68f](https://github.com/ockam-network/ockam/commit/314c68fe6c083de5c67475f9cd0e64b12cd50fdf) a better commit message would be something like:
> 
> 
> ```
> feat(rust): worker module
> 
> Define
> 1. Worker trait
> 2. ClosureWorker
> 3. Minimal WorkerContext
> ```

Cool, both done.

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by mrinalwadhwa** [comment]
since the two commits were squashed, I amended the commit message a little and merged https://github.com/ockam-network/ockam/commit/ccc626fe5bf482eae85b415b4a068da228bef0fe

**Pull request closed without merging**
