### PR TITLE
Node Context API refactor

### PR DESCRIPTION
**Pull request by spacekookie**
@jared-s I'll let you know when this PR has all required changes outlined in the MIro board

### CODE REVIEW

**Comment by jared-s** [comment]
Sounds good, thank you!

**Comment by jared-s** [comment]
For the rename of `Message::reply` to `return_route`, I think we probably want to keep `reply`with a:

```rust
#[deprecated(since = "0.8.0", note = "Please use the return_route function instead")]
```

For at least a few versions, since we have a lot of folks out there at the moment who have been going through the guide recently. After we update the guide source, we can rip it out.

**Comment by jared-s** [comment]
Eh, I'm sure it will be fine without deprecation at this point

**Comment by mrinalwadhwa** [comment]
Yes I think it fine without depreciation notice for our current preview releases

**Comment by spacekookie** [comment]
`5c84c27` should fix the issue where node panics when the main context goes out of scope. Could you test this @SanjoDeundiak ?

**Comment by jared-s** [comment]
Confirmed that the panic is fixed in my test scenario

**Comment by spacekookie** [comment]
:partying_face:

**Pull request merged**
