### PR TITLE
add `no_main` arg support in ockam::node macro

### LINKED ISSUE #2358: Change `no_main` feature on `ockam_macros` to an argument
Right now if [`no_main`](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_macros/Cargo.toml#L21-L24) is enabled on ockam_macros, it changes how the `ockam::node` macro is expanded.

However, it's reasonable for someone to have this enabled on one instance of the macro in a workspace, and not another, so we should change it to an argument rather than a feature. That is, I'm imagining something like `#[ockam::node(no_main)]`.

This doesn't require much ockam-specific experience, so I've marked it as "good first issue", but it probably does require familiarity with syn/proc macros.

### PR DESCRIPTION
**Pull request by pro465**
## Current Behaviour

the current behaviour is documented in #2358 .

## Proposed Changes

fixes #2358 .

## Checks

- [ ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
- [ ] All commits in this Pull Request follow the Ockam [commit message convention](https://www.ockam.io/learn/how-to-guides/contributing/CONTRIBUTING#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://www.ockam.io/learn/how-to-guides/high-performance-team/conduct/).
- [x] I have accepted the Ockam [Contributor Licence Agreement](https://www.ockam.io/learn/how-to-guides/contributing/cla/) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/ockam-network/contributors/blob/master/CONTRIBUTORS.csv) file in a separate pull request to the [ockam-network/contributors](https://github.com/ockam-network/contributors) repository.

### CODE REVIEW

**Comment by pro465** [comment]
well i guess this PR will be closed since i have ticked almost none of the checks...

**Comment by mrinalwadhwa** [comment]
Hi @pro465, thank you for sending this pull request ❤️.

No, If you could accept our CLA, a merge should be pretty easy from there.

  1. Read the CLA at: https://www.ockam.io/learn/how-to-guides/contributing/cla

  2. To accept the CLA, please send a different pull request to our
  [contributors repository](https://github.com/ockam-network/contributors) indicating that you accept
  the CLA by adding your Git/Github details in a row at the end of the
  [CONTRIBUTORS.csv](https://github.com/ockam-network/contributors/blob/main/CONTRIBUTORS.csv) file.

**Comment by pro465** [comment]
thank you for the instructions!

unfortunately, it looks like one of the node tests failed. i will try to fix that after school tho.

**Comment by mrinalwadhwa** [comment]
Awesome, thank you.
When you're ready here's how to make the [Commits check](https://github.com/ockam-network/ockam/runs/4597699766?check_suite_focus=true) pass:

```
git reset develop
git add .
git commit -m "feat(rust): add `no_main` arg support in `ockam::node` macro"
git push --force
```

**Comment by pro465** [comment]
thank you again for the instructions!

unfortunately, i have little time remaining to go to school, so i gotta go...

see you later!

**Comment by pro465** [comment]
@mrinalwadhwa hello, im back!

TODO:
- [ ] fix tests
- [ ] improve wording in case of invalid syntax (i.e, `#[ockam::node(time = 400)]`)
- [ ] sign commit + pass commit checks

**Comment by pro465** [comment]
i think that the failed test was literally matching the error message char by char, and so when the reported error changed, it failed.

but i could not find where the tests are located. could you help me here?

**Comment by mrinalwadhwa** [comment]
@pro465 that's right, the macro tests use [trybuild](https://github.com/dtolnay/trybuild) and are located here
https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam/tests/node

**Comment by thomcc** [comment]
We should also remove the `no_main` feature at the same time as this (since it should do nothing afterwards)

**Comment by pro465** [comment]
@thomcc well i guess that will be a breaking change, so that may require a major version bump.

let me add that to the TODO...

**Comment by pro465** [comment]
any suggestion for a better error message than just `invalid syntax for this macro`?

i could think of `'ockam::node' does not support this kind of syntax`

**Comment by mrinalwadhwa** [comment]
> 'ockam::node' does not support this syntax.
Hmm 🤔

Bumping version to 0.4.0.-dev makes sense cc: @jared-s please note.

One think to note - we don't allow merge commits in the develop branch so please rebase to develop whenever you're ready for a merge.

**Comment by pro465** [comment]
@mrinalwadhwa ok got it, thank you

**Comment by pro465** [comment]
gotta go to school. since school time should be enough for anyone to suggest a better error message, we will see after school hours.

see ya later!

**Comment by pro465** [comment]
@mrinalwadhwa hello, im back!

so, looks like nobody suggested a better error message

so, since your suggestion has the highest "votes" in this PR, im gonna apply that, and also change the test error message to that.

**Comment by pro465** [comment]
seems like im almost done. just need to check if the tests succed, and then, 

- [ ] force push it to pass the commit convention test
- [ ] sign the commit
- [ ] rebase it onto develop


and we should be good to go & merge!

**Comment by pro465** [comment]
so i found that the error told me to update the version specified for ockam_macros in ockam/Cargo.toml
and there i noticed that ockam itself has a no_main feature, so i removed that and bumped ockam's minor version to indicate breaking change.

hopefully the version bump will not break ockam...

**Comment by pro465** [comment]
off to school, bye!

**Comment by pro465** [comment]
> > 'ockam::node' does not support this syntax.
> 
> Hmm 🤔

@mrinalwadhwa 

hey, how about `unrecognized param passed`?

**Comment by pro465** [comment]
and btw, i tested the branch locally and fixed the failing test (due to typos), and `cargo check`-ed the repo. and it passed without any compile errors, so i think this should also pass the tests, since i did not change much things outside the scope of this PR...

basically, this should finally pass the workflows (except the commit checks)

**Comment by pro465** [comment]
@mrinalwadhwa done!

could you please tell me the next steps (after force-pushing to pass the commit checks) ?

**Comment by mrinalwadhwa** [comment]
@pro465 that should be it, looks like the only remaining check to pass in the commit linter.
https://github.com/ockam-network/ockam/runs/4630472803?check_suite_focus=true#step:5:89

Maybe squash all commits down to a single commit with this message:

```
feat(rust): add no_main arg support to ockam::node macro
```

And sign it.

**Comment by pro465** [comment]
seems like i dont have the gpg command, so i cant it yet...

**Comment by mrinalwadhwa** [comment]
Here's a tutorial from Github that may help
https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by pro465** [comment]
@mrinalwadhwa unfortunately, it didn't help :( i can't use or even install `gpg` through apt-get.

so i think i might need you to do that and open a PR to the forked repo; and, if necessary, transfer ownership of the forked repo to you, so that you can sign it and merge it yourself

**Comment by mrinalwadhwa** [comment]
@pro465 no problem, I can do the signing, could you squash all the changes down to a single commit please.

I'll sign and merge after that.

**Comment by pro465** [comment]
now we need to `git rebase develop`, right?

**Comment by mrinalwadhwa** [comment]
@pro465 I merged this in https://github.com/ockam-network/ockam/pull/2407
Congratulations and thank you for an awesome first contribution 🎉

**Comment by pro465** [comment]
@mrinalwadhwa thank you!

**Comment by pro465** [comment]
@mrinalwadhwa hey, we forgot to document about the possibility of `no_main` param in `ockam::node`!

**Pull request closed without merging**
