### PR TITLE
mrinal/ci cache

### PR DESCRIPTION
**Pull request by mrinalwadhwa**
- ci: remove action version comments
- ci: add cache composite action

### CODE REVIEW

**Comment by thomcc** [comment]
ISTM like we should use separate caches for cargo/target things and mix deps, since we have actions that do one, but not the other — this should avoid the issue I mentioned before about one cache wiping out the other.

**Comment by thomcc** [comment]
Oh, perhaps using the workflow/job in the cache key will do that too. Prevents sharing caches across jobs/workflows, but maybe that's not a big deal.

**Comment by mrinalwadhwa** [comment]
At first I thought scoping it to one job will not cause many unnecessary invalidations - but after your comment I gave it some more thought ... you're right, here's one case for example:

1. PR 10 changes elixir mix.lock
2. PR 11 changes only Rust code - this pr will get an invalid cache.

In the latest commit, I tried to setup caches specific to the what each job exactly needs.
But it seems my way of getting the docker image name didn't work. I'll fix that in a bit.

**Comment by thomcc** [comment]
To elaborate on what I mean by two caches — I did this when I set up imgui-rs's CI here: https://github.com/imgui-rs/imgui-rs/blob/main/.github/workflows/ci.yml#L37-L55. That said, it does it for .cargo and target separately — I think this is probably pointless, but for us it would make sense to have one cache for elixir, and one for Rust.

**Comment by mrinalwadhwa** [comment]
That's interesting, it makes sense I think for the elixir workflow to load two caches - Rust and Elixir.
Let me try.

**Comment by mrinalwadhwa** [comment]
Looks like we're down to ~20 minutes for the most time consuming actions with caching.
Without caching its ~35 minutes.
From here let's try all the things @thomcc highlighted in #2342 

```
» gh pr checks
All checks were successful
0 failing, 44 successful, 0 skipped, and 0 pending checks

✓  All - Build                                          20m0s   https://github.com/ockam-network/ockam/runs/4655005020?check_suite_focus=true
✓  All - Build                                          20m25s  https://github.com/ockam-network/ockam/runs/4655005490?check_suite_focus=true
✓  All - List Gradle Tasks (macos-10.15, 11)            30s     https://github.com/ockam-network/ockam/runs/4655005207?check_suite_focus=true
✓  All - List Gradle Tasks (macos-10.15, 11)            30s     https://github.com/ockam-network/ockam/runs/4655005875?check_suite_focus=true
✓  All - List Gradle Tasks (macos-10.15, 16)            53s     https://github.com/ockam-network/ockam/runs/4655005229?check_suite_focus=true
✓  All - List Gradle Tasks (macos-10.15, 16)            2m32s   https://github.com/ockam-network/ockam/runs/4655005890?check_suite_focus=true
✓  All - List Gradle Tasks (macos-10.15, 17)            28s     https://github.com/ockam-network/ockam/runs/4655005248?check_suite_focus=true
✓  All - List Gradle Tasks (macos-10.15, 17)            31s     https://github.com/ockam-network/ockam/runs/4655005912?check_suite_focus=true
✓  All - List Gradle Tasks (macos-10.15, 8)             50s     https://github.com/ockam-network/ockam/runs/4655005183?check_suite_focus=true
✓  All - List Gradle Tasks (macos-10.15, 8)             31s     https://github.com/ockam-network/ockam/runs/4655005845?check_suite_focus=true
✓  All - List Gradle Tasks (ubuntu-20.04, 11)           33s     https://github.com/ockam-network/ockam/runs/4655005129?check_suite_focus=true
✓  All - List Gradle Tasks (ubuntu-20.04, 11)           34s     https://github.com/ockam-network/ockam/runs/4655005711?check_suite_focus=true
✓  All - List Gradle Tasks (ubuntu-20.04, 16)           31s     https://github.com/ockam-network/ockam/runs/4655005147?check_suite_focus=true
✓  All - List Gradle Tasks (ubuntu-20.04, 16)           27s     https://github.com/ockam-network/ockam/runs/4655005778?check_suite_focus=true
✓  All - List Gradle Tasks (ubuntu-20.04, 17)           29s     https://github.com/ockam-network/ockam/runs/4655005159?check_suite_focus=true
✓  All - List Gradle Tasks (ubuntu-20.04, 17)           29s     https://github.com/ockam-network/ockam/runs/4655005813?check_suite_focus=true
✓  All - List Gradle Tasks (ubuntu-20.04, 8)            21s     https://github.com/ockam-network/ockam/runs/4655005103?check_suite_focus=true
✓  All - List Gradle Tasks (ubuntu-20.04, 8)            28s     https://github.com/ockam-network/ockam/runs/4655005693?check_suite_focus=true
✓  All - List Gradle Tasks (windows-2019, 11)           4m21s   https://github.com/ockam-network/ockam/runs/4655005334?check_suite_focus=true
✓  All - List Gradle Tasks (windows-2019, 11)           4m17s   https://github.com/ockam-network/ockam/runs/4655005963?check_suite_focus=true
✓  All - List Gradle Tasks (windows-2019, 16)           4m24s   https://github.com/ockam-network/ockam/runs/4655005341?check_suite_focus=true
✓  All - List Gradle Tasks (windows-2019, 16)           4m18s   https://github.com/ockam-network/ockam/runs/4655005977?check_suite_focus=true
✓  All - List Gradle Tasks (windows-2019, 17)           4m28s   https://github.com/ockam-network/ockam/runs/4655005352?check_suite_focus=true
✓  All - List Gradle Tasks (windows-2019, 17)           4m22s   https://github.com/ockam-network/ockam/runs/4655005994?check_suite_focus=true
✓  All - List Gradle Tasks (windows-2019, 8)            4m19s   https://github.com/ockam-network/ockam/runs/4655005313?check_suite_focus=true
✓  All - List Gradle Tasks (windows-2019, 8)            4m14s   https://github.com/ockam-network/ockam/runs/4655005939?check_suite_focus=true
✓  Commits - Check                                      22s     https://github.com/ockam-network/ockam/runs/4655005032?check_suite_focus=true
✓  Commits - Check                                      22s     https://github.com/ockam-network/ockam/runs/4655005509?check_suite_focus=true
✓  Documentation - Check Examples                       3m27s   https://github.com/ockam-network/ockam/runs/4655004935?check_suite_focus=true
✓  Documentation - Check Examples                       3m42s   https://github.com/ockam-network/ockam/runs/4655005512?check_suite_focus=true
✓  Editorconfig - Lint                                  11s     https://github.com/ockam-network/ockam/runs/4655004957?check_suite_focus=true
✓  Editorconfig - Lint                                  10s     https://github.com/ockam-network/ockam/runs/4655005456?check_suite_focus=true
✓  Elixir - Build                                       5m41s   https://github.com/ockam-network/ockam/runs/4655005034?check_suite_focus=true
✓  Elixir - Build                                       4m55s   https://github.com/ockam-network/ockam/runs/4655005437?check_suite_focus=true
✓  Elixir - Test                                        20m21s  https://github.com/ockam-network/ockam/runs/4655005110?check_suite_focus=true
✓  Elixir - Test                                        19m54s  https://github.com/ockam-network/ockam/runs/4655005654?check_suite_focus=true
✓  Rust - Build                                         18m35s  https://github.com/ockam-network/ockam/runs/4655004938?check_suite_focus=true
✓  Rust - Build                                         16m58s  https://github.com/ockam-network/ockam/runs/4655005651?check_suite_focus=true
✓  Rust - Check Cargo Update                            1m46s   https://github.com/ockam-network/ockam/runs/4655005099?check_suite_focus=true
✓  Rust - Check Cargo Update                            1m32s   https://github.com/ockam-network/ockam/runs/4655005434?check_suite_focus=true
✓  Rust - Check Features - no_std alloc software_vault  1m58s   https://github.com/ockam-network/ockam/runs/4655005135?check_suite_focus=true
✓  Rust - Check Features - no_std alloc software_vault  1m46s   https://github.com/ockam-network/ockam/runs/4655005784?check_suite_focus=true
✓  Rust - Test                                          7m32s   https://github.com/ockam-network/ockam/runs/4655005212?check_suite_focus=true
✓  Rust - Test                                          7m30s   https://github.com/ockam-network/ockam/runs/4655005898?check_suite_focus=true
```

**Pull request merged**
