### PR TITLE
chore(rust): Move `ockam_vault_test_suite` to `ockam_core::vault::test_support`

### PR DESCRIPTION
**Pull request by Jackbaude**
## Current Behaviour

The ockam_vault_test_suite crate tests the vault's behavior as its own crate.

## Proposed Changes

> ockam_vault_test_suite is a set of utilities that can be used to test an implementation of the core vault traits. We're moving these traits into ockam_core (in https://github.com/ockam-network/ockam/issues/2288), and tentatively we're going to move the test suite there too.

https://github.com/ockam-network/ockam/issues/2290

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://www.ockam.io/learn/how-to-guides/contributing/CONTRIBUTING#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://www.ockam.io/learn/how-to-guides/high-performance-team/conduct/).
- [x] I have accepted the Ockam [Contributor Licence Agreement](https://www.ockam.io/learn/how-to-guides/contributing/cla/) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/ockam-network/contributors/blob/master/CONTRIBUTORS.csv) file in a separate pull request to the [ockam-network/contributors](https://github.com/ockam-network/contributors) repository.

### CODE REVIEW

**Comment by Jackbaude** [comment]
Will this PR be reviewed?

**Comment by thomcc** [comment]
Can you fix the rustfmt complaint? And I'll review it tomorrow (I don't generally work weekends).

**Comment by Jackbaude** [comment]
Im not sure I understand the CI errors? How am I supposed to format the imports?

**Comment by thomcc** [comment]
Running `cargo fmt` generally should fix all formatting issues. Can you rebase also? Other than that this looks good.

**Comment by Jackbaude** [comment]
> Running `cargo fmt` generally should fix all formatting issues. Can you rebase also? Other than that this looks good.

What exactly do I need to rebase and how? Not sure really what im doing with that. Thank you for any help

**Comment by thomcc** [comment]
Hm, I guess it normally would be `git remote update && git rebase origin/develop` or something like this. I'll take care of it though.

**Comment by thomcc** [comment]
Hey, I've rebased and addressed a couple nits I had in #2579. Thanks for the contribution!!

**Pull request closed without merging**
