### PR TITLE
Improve demo usability

### PR DESCRIPTION
**Pull request by illaz**
Since I struggled by setting up the demo, I made some improvements to help other users to start up.

- Fix: Add missing packages to ockam-dev environment for running the demo
- Fix: Change docker image name for ockam-dev in rust router docker file
- Feature: Add script to easily setup the demo prerequisites
- Documentation: Add demo README

### CODE REVIEW

**Comment by nilslice** [comment]
@illaz - wow, thanks for the assist on this! looks like you found something that was merged a bit before it was ready for public use :) before we launch this, we will push the images to the docker registry which will help run the demo more smoothly. but it's great to have this setup script and set of instructions 👍  

A couple of minor tweaks are needed for us to be able to merge:

1. we require that all of our contributors accept the CLA, which a bot will reply with some instructions (if not, I'll add them in another comment). 

2. lastly, the commit message for `docs(demo): add demo README` is being caught by our linter. typically the `(demo)` "scope" you've included is great to have! however, "demo" isn't a supported scope (like "rust", "c", "elixir" etc). so in order for us to merge this, would you mind amending that commit to read as:

    `docs: add demo README`

Thank you again!

**Comment by nilslice** [comment]
recheckcla

**Comment by mattgreg** [comment]
Hey @illaz. This is amazing. Thanks for the help here.
Send me a DM with your address. I'd like to send you an Ockam Hat.

**Comment by illaz** [comment]
@nilslice 
> wow, thanks for the assist on this! looks like you found something that was merged a bit before it was ready for public use :) before we launch this, we will push the images to the docker registry which will help run the demo more smoothly. but it's great to have this setup script and set of instructions 👍

You're welcome! I knew I was working on the develop branch, so I didn't expect everything to work perfectly. I just wanted to try this demo so I made these changes ;)

>     1. we require that all of our contributors accept the CLA, which a bot will reply with some instructions (if not, I'll add them in another comment).

I saw the CLA check failed, but did not find the troubleshooting instructions. Would be great if you could add them.

>     2. lastly, the commit message for `docs(demo): add demo README` is being caught by our linter. typically the `(demo)` "scope" you've included is great to have! however, "demo" isn't a supported scope (like "rust", "c", "elixir" etc). and, `README` should be lowercased for consistency. so in order for us to merge this, I will amend that commit to read as:
>        `docs: add demo readme`

Sure, do I have to amend or do something?

@mattgreg You're welcome! I will send you a DM. Thank you 👍

**Comment by nilslice** [comment]
@illaz - I'm trying to fix the CLA bot, something broke & it's difficult to diagnose :) I will get to it ASAP. 

> Sure, do I have to amend or do something?

No, I'll just amend the commit message before I merge it in. Thank you though!

**Comment by mrinalwadhwa** [comment]
Hey @illaz we're still having some trouble with our CLA bot and are planning to set it up again from scratch, in the meantime would you be okay signing a CLA over email, so we can merge this PR?

**Comment by illaz** [comment]
@mrinalwadhwa Sorry for the late reply! Surely we can do signing a CLA over email. What do I have to do?

**Comment by jared-s** [comment]
Hi @illaz , we're improving the CLA process..for now, could you please submit a PR to https://github.com/ockam-network/contributors/blob/main/CONTRIBUTORS.csv with just one line adding yourself? As soon as that's done, we can fix up this PR. Thanks!

**Comment by jared-s** [comment]
Hi @illaz,
We ended up removing the underlying code for this demo as we iterate on our influxdb integration. Closing this PR since the changes cannot be applied to current develop. Thank you for taking the time to contribute!

**Pull request closed without merging**
