### PR TITLE
Sanjo/refactor tcp

### PR DESCRIPTION
**Pull request by SanjoDeundiak**

### CODE REVIEW

**Comment by jared-s** [comment]
Hmm, `rust_test_ockam_ockam_entity` has been running for 20 minutes. I wonder if an assertion failed and kept the Node alive. I'm unable to see logs at this point

**Comment by SanjoDeundiak** [comment]
> Hmm, `rust_test_ockam_ockam_entity` has been running for 20 minutes. I wonder if an assertion failed and kept the Node alive. I'm unable to see logs at this point

That's strange... Locally ockam_entity tests pass

**Comment by SanjoDeundiak** [comment]
By removing [serialize] from tunneling secure channel tests possibly fixes #1627

**Comment by SanjoDeundiak** [comment]
@jared-s let's merge it. Of we can merge tests fix first, and then come back to tcp refactoring

**Comment by jared-s** [comment]
Merged https://github.com/ockam-network/ockam/pull/1633

**Pull request closed without merging**
