### PR TITLE
feat(rust): Start new vault crate

### PR DESCRIPTION
**Pull request by mikelodder7**
Start a new crate for vault. Let me know if this structure is okay and if so I'll continue with it.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
the structure looks good 👍 
the commit linter want lower case commit messages. the rules are here https://github.com/ockam-network/ockam/blob/develop/commitlint.config.js

**Comment by mikelodder7** [comment]
odd. my commit message is all lowercase

**Comment by mikelodder7** [comment]
The error has something to do with Vagrant. See [here](https://dev.azure.com/ockam-network/ockam/_build/results?buildId=1664&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=bd05475d-acb5-5619-3ccb-c46842dbc997)

**Comment by mrinalwadhwa** [comment]
Thanks, just looked at the build log
https://dev.azure.com/ockam-network/ockam/_build/results?buildId=1664&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=bd05475d-acb5-5619-3ccb-c46842dbc997&l=3385

Does this have to do with the newly added crate?

```

   Compiling ockam-vault v0.1.0 (/vagrant/implementations/rust/vault)
   Compiling ockam-vault-sys v0.8.0 (/vagrant/implementations/rust/crates/ockam-vault-sys)
   Compiling ockam v0.8.0 (/vagrant/implementations/rust/crates/ockam)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/vagrant/implementations/rust/target/debug/deps/ockam_vault_sys-52044698ced42fd9.1edtumcprzy4i8fs.rcgu.o" "/vagrant/implementations/rust/target/debug/deps/ockam_vault_sys-52044698ced42fd9.24dg50kpbxb13xy1.rcgu.o" "/vagrant/implementations/rust/target/debug/deps/ockam_vault_sys-52044698ced42fd9.3cf5nc24v4pmqluf.rcgu.o" "/vagrant/implementations/rust/target/debug/deps/ockam_vault_sys-52044698ced42fd9.4dgg9p8hlsbtzx8i.rcgu.o" "/vagrant/implementations/rust/target/debug/deps/ockam_vault_sys-52044698ced42fd9.urnkzjknx7ujctj.rcgu.o" "-o" "/vagrant/implementations/rust/target/debug/deps/ockam_vault_sys-52044698ced42fd9" "/vagrant/implementations/rust/target/debug/deps/ockam_vault_sys-52044698ced42fd9.40j30mrpj54hj6ma.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/vagrant/implementations/rust/target/debug/deps" "-L" "/vagrant/implementations/rust/target/debug/build/ockam-vault-sys-ce6e216f900da611/out/ockam_vault/build/Debug/lib" "-L" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "-lockam_vault" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-lockam_vault_default" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-lockam_memory" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-lockam_random" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-lockam_random_urandom" "-Wl,--no-whole-archive" "/vagrant/implementations/rust/target/debug/deps/liblibc-6a54935c1aa17625.rlib" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-48cf79d5a79901bb.rlib" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm-bf84c77a9073903b.rlib" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-902f2c7ee89233ac.rlib" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-6ace3ed54c97ba6a.rlib" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-8ab2eab4fe2b9a29.rlib" "-Wl,--start-group" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-c32b051c3aafd36c.rlib" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-eabf8b29c0a244dd.rlib" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-5c336cc1b5ec2048.rlib" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-c7631f762b1ba6d9.rlib" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-db0f6c539591c951.rlib" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-32c2dc6fbc292c9c.rlib" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-84e9c510dc249620.rlib" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-13bc027534de0b4c.rlib" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-b3c13ecda1794c6c.rlib" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-72dc11de859645e9.rlib" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-a78b04f112feb31a.rlib" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-29469f6c53ac35f8.rlib" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-0eb3c513c640c4a6.rlib" "-Wl,--end-group" "/opt/rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-0b278345638bce90.rlib" "-Wl,-Bdynamic" "-lutil" "-ldl" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
  = note: /vagrant/implementations/rust/target/debug/deps/libockam_vault.a(ockam_vault.4mzh883eaairdgzq.rcgu.o): In function `__rust_alloc':
          4mzh883eaairdgzq:(.text.__rust_alloc+0x0): multiple definition of `__rust_alloc'
          /vagrant/implementations/rust/target/debug/deps/ockam_vault_sys-52044698ced42fd9.40j30mrpj54hj6ma.rcgu.o:40j30mrpj54hj6ma:(.text.__rust_alloc+0x0): first defined here
          /vagrant/implementations/rust/target/debug/deps/libockam_vault.a(ockam_vault.4mzh883eaairdgzq.rcgu.o): In function `__rust_alloc_zeroed':
          4mzh883eaairdgzq:(.text.__rust_alloc_zeroed+0x0): multiple definition of `__rust_alloc_zeroed'
          /vagrant/implementations/rust/target/debug/deps/ockam_vault_sys-52044698ced42fd9.40j30mrpj54hj6ma.rcgu.o:40j30mrpj54hj6ma:(.text.__rust_alloc_zeroed+0x0): first defined here
          /vagrant/implementations/rust/target/debug/deps/libockam_vault.a(ockam_vault.4mzh883eaairdgzq.rcgu.o): In function `__rust_dealloc':
          4mzh883eaairdgzq:(.text.__rust_dealloc+0x0): multiple definition of `__rust_dealloc'
          /vagrant/implementations/rust/target/debug/deps/ockam_vault_sys-52044698ced42fd9.40j30mrpj54hj6ma.rcgu.o:40j30mrpj54hj6ma:(.text.__rust_dealloc+0x0): first defined here
          /vagrant/implementations/rust/target/debug/deps/libockam_vault.a(ockam_vault.4mzh883eaairdgzq.rcgu.o): In function `__rust_realloc':
          4mzh883eaairdgzq:(.text.__rust_realloc+0x0): multiple definition of `__rust_realloc'
          /vagrant/implementations/rust/target/debug/deps/ockam_vault_sys-52044698ced42fd9.40j30mrpj54hj6ma.rcgu.o:40j30mrpj54hj6ma:(.text.__rust_realloc+0x0): first defined here
          collect2: error: ld returned 1 exit status
```

**Comment by mikelodder7** [comment]
Looks like it. There might be overlap with how I'm doing the naming. I'll change it from libockam_vault to something else temporarily.

**Comment by mrinalwadhwa** [comment]
merged.

**Pull request closed without merging**
