### PR TITLE
chore(rust): simplify tcp init process

### PR DESCRIPTION
**Pull request by feniks65**
### Proposed Changes

Rust - Implement a higher level TCP registration and initialization process

In this PR I wanted to address [#1161](https://github.com/ockam-network/ockam/issues/1161).

@jared-s 
What do you think of such a function?
Is there ockam_transport_tcp lib.rs correct place to put such a function?
Were you thinking of something different than just wrapping initialization and registration code into a public function?
In here, I am just returning `Context` and then `send_message()` can be called on this context.

### CODE REVIEW

**Comment by jared-s** [comment]
Hey @feniks65!

We just improved this API, in the latest `ockam_transport_tcp` crate release (and on develop). Now, all that is necessary is a call to `TcpTransport::create`. 

```rust
    // Get our peer address
    let peer_addr = get_peer_addr();

    // Initialize the TCP stack by opening a connection to a the remote
    TcpTransport::create(&ctx, &peer_addr).await?;

    // Send a message to the remote
    ctx.send(
        Route::new()
            .append_t(TCP, &peer_addr)
            .append("echo_service"),
        String::from("Hello you over there!"),
    )
    .await?;
````

It's a lot better. please give it a shot!

**Comment by jared-s** [comment]
The guides will be updated to reflect these new changes today.

**Comment by feniks65** [comment]
@jared-s 
Sure, I should have noticed that function `create()` is already in there.
So there is no need to simplifying anything now. `TcpTransport::create()` does the thing.

**Comment by jared-s** [comment]
Thanks for the suggestion though! Keep 'em coming!

**Pull request closed without merging**
