### PR TITLE
chore(rust): fix clippy warnings for profile, ockam_vault and ockam_vault_core

### PR DESCRIPTION
**Pull request by SanjoDeundiak**
Should cover everything in #857 
Other parts of code still have clippy problems...

### CODE REVIEW

**Review by jared-s — APPROVED** [review]

**Comment by jared-s** [comment]
@SanjoDeundiak Merged. We had all green and for some reason jobs restarted. I show `4c04` as develop HEAD now.

**Comment by jared-s** [comment]
@SanjoDeundiak hmmm this is concerning me that it says commits are still unmerged...investigating still.

**Comment by jared-s** [comment]
Nevermind, verified develop looks good. Not sure why GH is saying it is unmerged.

**Comment by SanjoDeundiak** [comment]
@jared-s whenever I have multiple related PRs, I create them like that:
PR1: branch1 -> develop
PR2: branch2 -> branch1
PR3: branch3 -> branch2
etc.
This may drive gh crazy

**Pull request closed without merging**
