### PR TITLE
feat(rust): initial ockam worker API

### PR DESCRIPTION
**Pull request by spacekookie**
A replacement PR for #843

### CODE REVIEW

**Comment by spacekookie** [comment]
I refactored all the changes into two commits because this makes the change much more coherent and atomic. Let me know if there's anything that needs changing in your opinion.

**Comment by mrinalwadhwa** [comment]
@spacekookie the changes here look good, thank you 🙏 
I'll merge this afternoon.

The build failure in unrelated.

**Comment by jared-s** [comment]
Build being fixed here: https://github.com/ockam-network/ockam/pull/861

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by jared-s** [comment]
Merged in https://github.com/ockam-network/ockam/pull/861

**Pull request closed without merging**
