### PR TITLE
chore: change the word 'Option' to 'Feature' in Cargo.toml files

### LINKED ISSUE #1796: Use the word "Feature" when documenting features in Cargo.toml files
Currently we use the word "Option" which is inconsistent and may cause confusion.

Example:

```toml
# Option: "alloc" enables support for heap allocation on "no_std"
# platforms, requires nightly.
alloc = ["ockam_core/alloc", ...
```

Should rather be:

```toml
# Feature: "alloc" enables support for heap allocation on "no_std"
# platforms, requires nightly.
alloc = ["ockam_core/alloc", ...
```

### PR DESCRIPTION
**Pull request by jim4067**
### Proposed Changes
Changed the world 'Option' to 'Feature' in Cargo.toml files to mantain consistency avoid confusion. 

Resolves #1796

### CODE REVIEW

**Comment by antoinevg** [comment]
Thank you for contributing to the project Jimmy. Go Uonbi! 

Just two small things needed to get your PR to conform to our [guidelines](https://www.ockam.io/learn/how-to-guides/contributing/CONTRIBUTING):

1. Please squash the two commits in your PR into a single commit: [A Beginner’s Guide to Squashing Commits with Git Rebase](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec)
2. Please remove all capital letters from your commit: `chore: change the word 'option' to 'feature' in cargo files`

**Comment by jim4067** [comment]
Okay. on it 👍🏾

**Comment by mrinalwadhwa** [comment]
@jim4067 Thank you for sending the PR 🙏 
I noticed you were struggling with the rebase and squash ... this is what I did

```
git rebase develop
git reset develop
git commit --author="jim4067 <jimmyimpulse2@gmail.com>" --date="Sun Aug 29 16:26:58 2021 +0300"
```

That last step could've been a `git commit --amend` instead of reset and commit.

I rebased, squashed and merged in https://github.com/ockam-network/ockam/pull/1812

Congratulations on your first Ockam contribution 🥳  🎉

**Comment by jim4067** [comment]
Thanks. It was my first time using rebase. Getting more familiar with new git commands everyday.

Thanks 👍

**Pull request closed without merging**
