### PR TITLE
feat(rust):add key validation during secret_import in ockam_vault

### PR DESCRIPTION
**Pull request by SanjoDeundiak**

### CODE REVIEW

**Comment by SanjoDeundiak** [comment]
It looks like Noise XX Key Agreement test vectors were generated by using invalid predefined keys. Need to update those values before we can merge it
We'll need to update those values in elixir as well cc @hairyhum @mrinalwadhwa

**Comment by devalain** [comment]
Hey @SanjoDeundiak, may I do something about it ?

**Comment by SanjoDeundiak** [comment]
> Hey @SanjoDeundiak, may I do something about it ?

Hey @devalain . If you want to update xx test vectors - you're welcome to do so. It would be great!

**Comment by devalain** [comment]
Hope I did it right.

**Comment by SanjoDeundiak** [comment]
#1695

**Pull request closed without merging**
