### PR TITLE
Rust Software Vault Progress

### PR DESCRIPTION
**Pull request by hollyfeld**
### For Review Only

This PR begins implementation of issue #149. There will be additional
commentary soon on the issue itself for further discussion on architecture.

- The goal of this PR is to get a review/discussion around the initial setup and course correct as needed before implementing other default vault methods.

- Specifically, this pull request sets up traits for Random and Vault, along with basic implementations, tests, an example, and some doc. There will be additions to all areas after review.

- The current Default Vault C implementation was used as a model, while trying to avoid anything un-rustlike.

- Currently no_std is used without a heap allocator, and no methods are derived. In general, the current thinking is to keep the implementation as basic as possible, and build up as needed.

Thanks!

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@hollyfeld thank you for working on this 🙏 
I'll read the code and share some thoughts/questions over the next couple of days.

**Comment by hollyfeld** [comment]
@mrinalwadhwa I'm going to close this for now as it is getting stale. I still plan to request an incremental review(s), but it makes more sense to finish up some work I have in progress and open an new PR at that time.

**Comment by mrinalwadhwa** [comment]
@hollyfeld thank you, we added @mikelodder7 to the team today who brings great Rust and Cryptography expertise to the team. We can now help give feedback faster and break this effort down.

We also want to think about changing the stack from `Elixir > Rust > C` to `Elixir > C > Rust` so there will be some major restructuring over the next couple of weeks.

**Comment by hollyfeld** [comment]
@mrinalwadhwa sounds great. Hello @mikelodder7!

**Pull request closed without merging**
