### PR TITLE
Fix windows build

### PR DESCRIPTION
**Pull request by SanjoDeundiak**
Use static cmocka library for tests. Enable windows CI build. Fix for #237 and #265

### CODE REVIEW

**Comment by SanjoDeundiak** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by SanjoDeundiak** [comment]
@mrinalwadhwa after your recent gradle changes CI build on windows started to use MVSC compiler (instead of gcc), which caused new problems with build (e.g. absence of pthread). Do we want to be able to build with gcc on windows (which should be possible with this PR), or make everything work with mvsc?

**Comment by SanjoDeundiak** [comment]
#262

**Comment by mrinalwadhwa** [comment]
That's really interesting. The gradle changes from last night make it so that gradle doesn't pick the default CMake generator. Instead CMake picks the default generator.

The idea there is that we want to test for / optimize the default experience most people will have on a platform.

In case of windows (or at least the windows ci machine) it seems CMake picked the Visual Studio generator. Which also picks visual studio's default compiler.

For this PR let's change `ci.yml` to specify `Unix Makefiles` generator when the OS is windows.

```
../../gradlew build -PcmakeGenerator="Unix Makefiles"
```

**Comment by mrinalwadhwa** [comment]
@SanjoDeundiak I forgot to mention, the test run needs the `cmakeGenerator` option too

**Comment by mrinalwadhwa** [comment]
It took me a second to realize why the github workflow didn't run
https://github.com/ockam-network/ockam/actions/runs/184488829#L26

**Pull request merged**
