### PR TITLE
feat(elixir): add tracing service to trace payloads

### PR DESCRIPTION
**Pull request by hairyhum**
### Proposed Changes

Add a new service to trace messages going through the Hub.

A tracing address is registered same way as forwarding address
Registered tracing address worker copies payloads to the registered route

### CODE REVIEW

**Comment by hairyhum** [comment]
Added a `RemoteTracer` rust worker as a copy of `RemoteForwarder` with some renames. 
We might generalize the pattern of registration, but before that I didn't feel confident reusing the code there since it's a different thing, although with exactly same behaviour.
@jared-s @SanjoDeundiak WDYT?

**Review by jared-s — APPROVED** [review]
Worker implementation looks good to me, agree it's the right approach to split this instead of trying to DRY it up with the forwarding code. 

I'm imagining this may power the log view of the Hub UI, and serve as a general debug ability? Anything else building upon this tracing feature?

**Comment by hairyhum** [comment]
It's not intended to be used in Hub UI, as logging messages in the Hub UI has a number of issues like access control, filtering and performance.
This was an attempt to shift the message logs to the client application instead.

**Comment by SanjoDeundiak** [comment]
@hairyhum do you still want to merge it? Or are we closing it?

**Comment by hairyhum** [comment]
I'd like to merge the service. It's going to be useful in future examples. @SanjoDeundiak @jared-s your call whether to merge the Rust worker, I can remove it.

**Comment by jared-s** [comment]
The worker's fine with me to merge. Just need to take care of these CI failures. Let me know if you need help with any of them. Some may be similar to the guide branch which I'm looking at now

**Comment by jared-s** [comment]
The action failures related to `remote_forwarder.rs` should be fixed in [this commit](https://github.com/ockam-network/ockam/commit/f0a46e971babb1d406b26970309d4fa668d47469), which should be easy to either cherry pick over to here or merge to develop first and rebase to here.

**Comment by SanjoDeundiak** [comment]
@hairyhum we definitely don't want to mix rust and elixir changes in one commit. My suggestion is we move elixir changes to separate commit&PR, and elixir team is reviewing and merging it. Then we can discuss again why we need RemoteTracer in rust.

**Comment by hairyhum** [comment]
Extracted rust changes to https://github.com/ockam-network/ockam/pull/1598

**Pull request merged**
