### PR TITLE
ockam_hub

### PR DESCRIPTION
**Pull request by mrinalwadhwa**

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@nilslice I'll have more changes for ockam_hub later but everything here is ready for review and can be merged after your review.

The docker setup here duplicates some of work in the ockam-dev container... I needed something that could run the C, Rust, Elixir builds successfully and didn't want to disrupt your other containers.

We can resolve the diffs later and turn it into one container.

Instructions to try the containers, from the root of the repo.

```
docker build -t ockam/builder -f tools/docker/elixir/builder/Dockerfile . docker build --target ockam_hub_build -t 
ockam/ockam_hub/build -f implementations/elixir/ockam/ockam_hub/Dockerfile . docker build --target ockam_hub -t 
ockam/ockam_hub -f implementations/elixir/ockam/ockam_hub/Dockerfile .
```

**Comment by nilslice** [comment]
@mrinalwadhwa no problem re: Dockerfiles -- mine was definitely not complete so this is really helpful. As far as I can tell 

commit message typo: `feat(elixir): imporve udp transport`, `s/imporve/improve`

**Comment by mrinalwadhwa** [comment]
Thanks for catching that, fixed.

**Comment by mrinalwadhwa** [comment]
@nilslice once this succeeds in CI, try this:

From project root:
```
./gradlew veryClean
```

Remove any cached images or layers and then build the containers again.

**Review by nilslice — APPROVED** [review]

**Pull request merged**
