### PR TITLE
test(rust): add test for examples/rust/tcp_inlet_and_outlet

### PR DESCRIPTION
**Pull request by neil2468**
## Current Behaviour
The script ockam/tools/docs/run_examples.sh tests some example code but does not run tests on ockam/examples/rust/tcp_inlet_and_outlet.

## Proposed Changes
Add tests so that tcp_inlet_and_outlet code is tested. This is related to #2256. This requires updating the shell script (run_examples.sh), the test runner (example_runner), and the scripts read by the test runner (*.ron).

Some notes...
- It appears the Docker image does not include python3, so, just in case, these new tests use ockam.io:80 as a HTTP endpoint when testing (instead of launching a local python3 HTTP server, as Ockam guides suggest).
- The test harness will now stop as soon as a test fails and will exit with a non-0 code.
- A test (aka stage) will fail if a spawned process exits with an error, or if a 'match' attempt times out (currently 120 seconds).
- I believe this test harness *may* be being run as part of the GitHub CI. And as the Kafka example tests use the HTTP endpoint 1.node.ockam.network:4000, I assume tests running in CI will also be able to access ockam.io:80.

## Checks
- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://www.ockam.io/learn/how-to-guides/contributing/CONTRIBUTING#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://www.ockam.io/learn/how-to-guides/high-performance-team/conduct/).
- [x] I have accepted the Ockam [Contributor Licence Agreement](https://www.ockam.io/learn/how-to-guides/contributing/cla/) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/ockam-network/contributors/blob/master/CONTRIBUTORS.csv) file in a separate pull request to the [ockam-network/contributors](https://github.com/ockam-network/contributors) repository.

### CODE REVIEW

**Review by thomcc — APPROVED** [review]
Looks great (assuming green CI), thanks!

**Comment by thomcc** [comment]
Can you trim the trailing whitespace in the `.ron` files? Thanks.

**Comment by neil2468** [comment]
I've updated the PR (at least I think I have). It should now contain the whitespace edits and a rebase of recent changes from ockam.

I'm new to PRs. Thanks for your patience!

**Comment by neil2468** [comment]
I see the 'Documentation - Check Examples' check has been struggling. 

To my eye it looks like the job is using the new run_examples.sh and *.ron files but is using an old binary for example_runner.

Currently, run_example.sh only builds example_runner if 'which example_runner' returns nothing (i.e. it's not been built and cargo installed). Run_example could be chnaged to always uninstall, build, and install example_runner.

Hope that helps.

**Comment by thomcc** [comment]
Oh, wow, yeah that's not great. I have some incoming changes to example runner, but they're a few days off at least (and that's assuming I don't get swamped with other stuff).

For now, do you mind changing run_examples.sh to something like this?

```sh
#!/usr/bin/env bash

if [ -z $OCKAM_HOME ]; then
    echo "Please set OCKAM_HOME to the repo root"
    exit -1
fi

export TOOLS_DIR="$OCKAM_HOME/tools/docs"
export GET_STARTED="$OCKAM_HOME/examples/rust/get_started/"
export GET_STARTED_SCRIPT="$TOOLS_DIR/example_runner/get_started.ron"

pushd $GET_STARTED
echo $GET_STARTED_SCRIPT
cargo run -p example_runner -- $GET_STARTED_SCRIPT
popd
```

**Comment by thomcc** [comment]
(Yeah, there are a bunch of things in that script that are still not ideal, like needless `export`s and requiring `OCKAM_HOME` rather than just using `git rev-parse --show-top-level`, but I'll take care of them later)

**Review by thomcc — APPROVED** [review]
Looks great, thanks a ton for the contribution (and the patience working through the issues).

**Comment by mrinalwadhwa** [comment]
@neil2468 Thank you for another awesome contribution.

**Comment by neil2468** [comment]
One thought: I don't know if the GitHub CI would be able to detect a 'Documentation - Check Examples' failure (apart from timeout due to hang). 

I think, the scripts run_example.sh and run_kafka_example.sh may be stopping any failure exit codes from bubbing to the script caller. So the CI may always see exit code 0.

**Pull request merged**
