### PR TITLE
feat(rust): implement more os x vault methods

### PR DESCRIPTION
**Pull request by mikelodder7**

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@mikelodder7 lets disable clippy for the time being and merge the PRs that are blocked. Disabling clippy will make their checks pass.

**Comment by mrinalwadhwa** [comment]
@mikelodder7 for formatting commits please use the `style` scope 
https://github.com/ockam-network/ockam/blob/develop/commitlint.config.js#L58-L59

**Comment by mikelodder7** [comment]
> @mikelodder7 lets disable clippy for the time being and merge the PRs that are blocked. Disabling clippy will make their checks pass.

Clipp isn't stopping it. Its the formatting and that shouldn't be disabled

**Comment by mrinalwadhwa** [comment]
I meant to say, whatever is failing the build, let's disable it so these PRs can merge, and log an issue describing why the CI build may be failing.

**Review by mrinalwadhwa — APPROVED** [review]

**Pull request merged**
