### PR TITLE
Minor fixes: correct example file name, remove incorrect "Next" link.

### PR DESCRIPTION
**Pull request by sateeshkumarb**
### Proposed Changes

 Corrected the example file name, remove incorrect "Next" link which was pointing to Example 6.

### CODE REVIEW

**Comment by jared-s** [comment]
Thank you @sateeshkumarb, those edits were intended for the website repo and I had wondered where I had put them!

**Comment by jared-s** [comment]
Thanks for fixing these @sateeshkumarb!  Before we can merge, could you accept our CLA? It's a quick process:

Read the CLA at
https://www.ockam.io/learn/how-to-guides/contributing/cla/

To accept the CLA please send a different PR to our contributors repo indicating that you accept the CLA by adding your Git/Github details in a row at the end of the CONTRIBUTORS.csv file:
https://github.com/ockam-network/contributors/blob/master/CONTRIBUTORS.csv

**Comment by jared-s** [comment]
One more thing, could you please [sign this commit](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/signing-commits)? Please ensure that the email address of the signing GPG key is the same email address that is used when accepting the CLA. Thanks again!

**Comment by sateeshkumarb** [comment]
@jared-s I have accepted the CLA and here is the PR for the same: https://github.com/ockam-network/contributors/pull/22.
I have signed the commit. In both these PRs (this one, and the one created against the contributors repo) the initial commits are unsigned, as I had not configured GPG etc. when I did those commits. I hope the initial commits being shown as _Unverified_ is fine, if not please let me know. I will close the PRs and create ones with fresh signed commits, as the changes are not huge. Thanks.

**Comment by mrinalwadhwa** [comment]
@sateeshkumarb after the CLA commit history is fixed, we can easily fix the history here.

The steps, just like the [CLA fix ](https://github.com/ockam-network/contributors/pull/22)are:

```
git reset --hard 522f9a6074d23a3b030651e170053eb2e1c0648e # hash of the commit we want to keep
git reset --soft HEAD~1
git commit
```

Then `git push --force` to your fork.

**Comment by sateeshkumarb** [comment]
@mrinalwadhwa I have fixed the commit history. Thanks.

**Comment by mrinalwadhwa** [comment]
I merged 1cb82407ce82d7e2e93d76ef484a07f5086f643e with some minor edits to the commit message.
Congratulations on your first contribution to Ockam 🎉

**Pull request closed without merging**
