### PR TITLE
ockam_credential crate v0.1.0

### PR DESCRIPTION
**Pull request by jared-s**
# ockam_credential crate v0.1.0

Pre-release PR for the `ockam_credential` crate.

- Doc fixes
- Clippy Fixes
- Tests

### CODE REVIEW

**Comment by jared-s** [comment]
@mikelodder7 please have a look. Mostly cosmetic, but a few small changes to make Clippy happy.

**Review by mikelodder7 — APPROVED** [review]

**Comment by mrinalwadhwa** [comment]
```
» cargo +nightly clippy --all-targets  -- -D warnings
    Checking ockam_credential v0.1.0 (/Users/mrinal/Workspace/ockam-network/ockam/implementations/rust/ockam/ockam_credential)
error: calls to `push` immediately after creation
  --> src/lib.rs:75:9
   |
75 | /         let mut attributes = Vec::new();
76 | |
77 | |         attributes.push(attribute);
   | |___________________________________^ help: consider using the `vec![]` macro: `let mut attributes = vec![..];`
   |
note: the lint level is defined here
  --> src/lib.rs:27:5
   |
27 |     warnings
   |     ^^^^^^^^
   = note: `#[deny(clippy::vec_init_then_push)]` implied by `#[deny(warnings)]`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#vec_init_then_push

error: aborting due to previous error

error: could not compile `ockam_credential`

To learn more, run the command again with --verbose.
```

**Comment by mrinalwadhwa** [comment]
```
» cargo +nightly clippy --all-targets --all-features  -- -D warnings
    Checking ockam_credential v0.1.0 (/Users/mrinal/Workspace/ockam-network/ockam/implementations/rust/ockam/ockam_credential)
error[E0308]: mismatched types
  --> src/lib.rs:70:20
   |
70 |             label: String::from("test_attr"),
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `heapless::String`, found struct `alloc::string::String`
   |
   = note: expected struct `heapless::String<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UTerm, heapless::consts::B1>, heapless::consts::B0>, heapless::consts::B0>, heapless::consts::B0>, heapless::consts::B0>, heapless::consts::B0>>`
              found struct `alloc::string::String`

error[E0308]: mismatched types
  --> src/lib.rs:71:26
   |
71 |             description: String::from("test attribute"),
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `heapless::String`, found struct `alloc::string::String`
   |
   = note: expected struct `heapless::String<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UTerm, heapless::consts::B1>, heapless::consts::B0>, heapless::consts::B0>, heapless::consts::B0>, heapless::consts::B0>, heapless::consts::B0>>`
              found struct `alloc::string::String`

error[E0308]: mismatched types
  --> src/lib.rs:80:17
   |
80 |             id: String::from("test_id"),
   |                 ^^^^^^^^^^^^^^^^^^^^^^^ expected struct `heapless::String`, found struct `alloc::string::String`
   |
   = note: expected struct `heapless::String<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UTerm, heapless::consts::B1>, heapless::consts::B0>, heapless::consts::B0>, heapless::consts::B0>, heapless::consts::B0>, heapless::consts::B0>>`
              found struct `alloc::string::String`

error[E0308]: mismatched types
  --> src/lib.rs:81:20
   |
81 |             label: String::from("test_label"),
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `heapless::String`, found struct `alloc::string::String`
   |
   = note: expected struct `heapless::String<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UTerm, heapless::consts::B1>, heapless::consts::B0>, heapless::consts::B0>, heapless::consts::B0>, heapless::consts::B0>, heapless::consts::B0>>`
              found struct `alloc::string::String`

error[E0308]: mismatched types
  --> src/lib.rs:82:26
   |
82 |             description: String::from("test_desc"),
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `heapless::String`, found struct `alloc::string::String`
   |
   = note: expected struct `heapless::String<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UTerm, heapless::consts::B1>, heapless::consts::B0>, heapless::consts::B0>, heapless::consts::B0>, heapless::consts::B0>, heapless::consts::B0>>`
              found struct `alloc::string::String`

error[E0308]: mismatched types
  --> src/lib.rs:83:13
   |
83 |             attributes,
   |             ^^^^^^^^^^ expected struct `heapless::Vec`, found struct `alloc::vec::Vec`
   |
   = note: expected struct `heapless::Vec<attribute::Attribute, typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UTerm, heapless::consts::B1>, heapless::consts::B0>, heapless::consts::B0>, heapless::consts::B0>, heapless::consts::B0>, heapless::consts::B0>>`
              found struct `alloc::vec::Vec<attribute::Attribute>`

error: aborting due to 6 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `ockam_credential`

To learn more, run the command again with --verbose.
```

**Comment by jared-s** [comment]
@mrinalwadhwa it looks like something is confusing the clippy toolchain. The unit tests, which this is flagging, run in std mode, not with heapless.

**Comment by mrinalwadhwa** [comment]
merged

**Pull request closed without merging**
