### PR TITLE
docs: fix typo in enrollment document

### PR DESCRIPTION
**Pull request by xtian**
### Proposed Changes
Just fixing a small typo I noticed while reading through the docs.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@xtian thank you for sending the PR ❤️

Before we can merge, could you accept our CLA

Read the CLA at
https://www.ockam.io/learn/how-to-guides/contributing/cla/

To accept the CLA please send a different PR to our contributors repo indicating that you accept the CLA by adding your Git/Github details in a row at the end of the CONTRIBUTORS.csv file:
https://github.com/ockam-network/contributors/blob/master/CONTRIBUTORS.csv

Looking forward to merging your first contribution!!

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by xtian** [comment]
@mrinalwadhwa Sure thing! https://github.com/ockam-network/contributors/pull/2

**Comment by mrinalwadhwa** [comment]
Thank you 🎉

**Comment by mattgreg** [comment]
Welcome to the Ockam community @xtian

**Pull request merged**
