### PR TITLE
elixir build improvements

### PR DESCRIPTION
**Pull request by mrinalwadhwa**
- build(elixir): update mix.lock in ockam_transport_udp
- style(elixir): fix credo warnings
- build(elixir): make gradle build all elixir apps
- fix(elixir): broken tests in ockam app
- fix(elixir): broken test in ockam_transport_udp
- build(elixir): disable ockam_vault_software in gradle build
- docs(elixir): disable module docs for node web socket
- build(elixir): ensure gradle lint, build and test run after deps_get
- ci: setup elixir and update pinned actions

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@nilslice this PR branch is based on your branch in #535 because I needed the changed order.
Please merge it after 535.

**Comment by mrinalwadhwa** [comment]
Here is the test to run when reviewing this PR:

From the root of Ockam repo:
```
./gradlew lint
./gradlew build
./gradlew test
./gradlew clean
```

This is what CI is now doing and elixir is integrated back into the gradle build.

**Comment by mrinalwadhwa** [comment]
This PR also fixes #525

**Review by nilslice — APPROVED** [review]
all 4 `gradlew` commands work 👍

**Review by nilslice — APPROVED** [review]

**Pull request merged**
