### PR TITLE
chore(rust): add secure channel tunneling tests

### PR DESCRIPTION
**Pull request by feniks65**
### Proposed Changes

Add test to ensure secure channel tunneling works in the rust implementation

@mrinalwadhwa 
I wanted to write tests for secure channel tunneling, for the rust implementation to fix the issue [#1410](https://github.com/ockam-network/ockam/issues/1410).

Is this the thing that you had in your mind?

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
Hey @feniks65 👋 thanks for picking this up and sending the PR ❤️ 
After a quick glance that looks pretty close to what I was looking for ... I'll read it in more detail later today and come back with any feedback.

Thank you 🙏

**Comment by SanjoDeundiak** [comment]
Found bug in our code tnx to this tests, see #1611 . Thanks @feniks65 
Rebased and pushed these changes. See #1613

**Comment by mrinalwadhwa** [comment]
@feniks65 thank you for this contribution and sorry about being slow on merging this 🙏 
This was merged 3384989063110002ac295b8fabe9377166e7d2c5

**Comment by feniks65** [comment]
I have stuck with this issue thinkin that there was a bug in my tests, that is why I didn't know what should I do with this.
@SanjoDeundiak thanks for sharing the feedback that it somehow helped to find a bug in the code base.

**Comment by mrinalwadhwa** [comment]
Thank you for that, we were refactoring heavily to launch a new set of guides and examples next week, for features like Entities, Streams and Kafka integration ... and lost track of this PR.

**Pull request closed without merging**
