### PR TITLE
Remove bashisms

### PR DESCRIPTION
**Pull request by lorrin**
### Proposed Changes
Small fix: demo script shebang only specifies `sh`, but script had some bashisms (`[[ ... ]]` conditionals) and thus failed to run on systems were bash was not the default shell. Changed to simple POSIX (`[ ... ]` conditionals).

(Unrelated) Also fix broken link to contributing guidelines.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
Thanks @lorrin ❤️ 

The changes look good to merge.
Something's up with our CLA bot, I'll check and get back to you on what's up there.

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by mattgreg** [comment]
@lorrin Since our CLA Check bot has a bug and is blocking the merge here, I've sent you a Docusign as an alternative to this automated flow. Once you sign the Docusign we can manually merge this contribution. Thanks for the patience

**Comment by lorrin** [comment]
Seems like maybe the bot is back in business? Let me give it a try.

**Comment by lorrin** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by lorrin** [comment]
recheckcla

**Comment by lorrin** [comment]
Seems like the bot worked, though its link needs updating from https://www.ockam.io/learn/guides/contributions/cla to https://www.ockam.io/learn/how-to-guides/contributing/cla

**Comment by mrinalwadhwa** [comment]
@lorrin thank you so much for sending this PR and being patient with our CLA bot problems.

I just merged the PR with some minor edits to the commit message, made sure you attribution is maintained https://github.com/ockam-network/ockam/commit/a3611c27b71370f252cd4293492451372ad1e208.

Thank you 🙏

**Pull request closed without merging**
