### PR TITLE
Fix grade tasks on Windows

### PR DESCRIPTION
**Pull request by BlackHoleFox**
## Current Behaviour

Running `../../gradlew lint` from an implementation folder doesn't work on Windows and crashes the gradle build:
```
A problem occurred configuring root project 'rust'.
> Could not create task ':__build_ockam\ockam_0'.
   > The task name '__build_ockam\ockam_0' must not contain any of the following characters: [/, \, :, <, >, ", ?, *, |]
   ```
## Proposed Changes
This PR changes up how paths are handled building the gradle tasks. Instead of using bash(sh?)-isms and hardcoding `/` as the path seperator, use the platform's separator and use platform-agnostic methods to read directory contents. This lets it work on both UNIX systems and Windows. 

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://www.ockam.io/learn/how-to-guides/contributing/CONTRIBUTING#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://www.ockam.io/learn/how-to-guides/high-performance-team/conduct/).
- [x] I have accepted the Ockam [Contributor Licence Agreement](https://www.ockam.io/learn/how-to-guides/contributing/cla/) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/ockam-network/contributors/blob/master/CONTRIBUTORS.csv) file in a separate pull request to the [ockam-network/contributors](https://github.com/ockam-network/contributors) repository. (It is [here](https://github.com/ockam-network/contributors/pull/52))

(having a bit of a night with the commit lint, sorry)

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@BlackHoleFox awesome, thank you for fixing this!
Could you also enable the windows targets in this Github Workflow. That way, we'll get a test in CI
https://github.com/ockam-network/ockam/blob/develop/.github/workflows/gradle.yml#L25

**Comment by BlackHoleFox** [comment]
oh I didn't see that, good idea. I enabled both 2016 and 2019 server in the matrix.

**Comment by mrinalwadhwa** [comment]
@BlackHoleFox Thank you for an awesome first contribution!! 🎉 
I made a minor trailing space edit and merged in #2246.

**Comment by mrinalwadhwa** [comment]
@BlackHoleFox I had to undo some of this, for the time being, in https://github.com/ockam-network/ockam/commit/07c6c0df17cd908722263869e5f6f7e6aef0854e since it was breaking some of the Elixir builds in CI

Here's an example case that breaks:
```
cd implementations/elixir && ../../gradlew build 
```

I'll explore more in my morning ... for the time being an undo was a quick fix to stop CI from failing.

**Comment by BlackHoleFox** [comment]
@mrinalwadhwa Sorry about that, ouch. I don't have Elixir setup at all locally so I just ran the Rust jobs. I was kind of hoping CI would make sure that I didn't break the system :sweatblob:

**Comment by mrinalwadhwa** [comment]
@BlackHoleFox oh ya, not your fault at all ... CI should've caught it. 
We have some things to fix there - I filed https://github.com/ockam-network/ockam/issues/2248.

In case you have time to explore this ... and want an easy setup ... this will give you the same docker environment CI is running it. It has elixir, rust and other tools that our builds use (it's a big ~2GB download though)

```
docker run --rm -it -e HOST_USER_ID=$(id -u) --volume $(pwd):/work ghcr.io/ockam-network/ockam/builder:latest bash
```

**Pull request closed without merging**
