### PR TITLE
docs:(rust): Minor updates to Getting Started Guide

### PR DESCRIPTION
**Pull request by jjscheel**
Updates per Issue #1309.

Signed-off-by: Jeff Scheel <jjscheel68@gmail.com>

### CODE REVIEW

**Comment by jared-s** [comment]
Awesome, thanks @jjscheel! I'll rebase this and get it merged. 

One quick thing: we have pretty strict lint rules for the commit messages - would you mind lower casing everything in the message? That should stop it from complaining. Thanks!

**Comment by mrinalwadhwa** [comment]
Thank you for sending the PR ❤️

Before we can merge, could you accept our CLA

Read the CLA at
https://www.ockam.io/learn/how-to-guides/contributing/cla/

To accept the CLA please send a different PR to our contributors repo indicating that you accept the CLA by adding your Git/Github details in a row at the end of the CONTRIBUTORS.csv file:
https://github.com/ockam-network/contributors/blob/master/CONTRIBUTORS.csv

Looking forward to merging your first contribution!!

**Comment by jared-s** [comment]
Fixing the commit up in PR https://github.com/ockam-network/ockam/pull/1311 - After we get the CLA merged we will be good to go!

**Comment by jjscheel** [comment]
Should be done.
-Jeff

**Comment by jjscheel** [comment]
Sorry about the Lint failures.  I did my best to follow the "Commit Messages" documentation but didn't see anything that said to use all lowercase.  Does that include EVERYTHING in the commit message?

**Comment by jared-s** [comment]
No problem! This last lint message was for some stray space at the end of a line. I've fixed it up in this PR https://github.com/ockam-network/ockam/pull/1311 which i'll merge as soon as it's done building. Thanks again for your help!

**Comment by jjscheel** [comment]
Yeah, I noticed that too.  I'll look at running eclint before I submit
again.

**Comment by jared-s** [comment]
Merged as https://github.com/ockam-network/ockam/pull/1311 :tada:

**Pull request closed without merging**
