### PR TITLE
feat(rust): add ffi layer for vault

### PR DESCRIPTION
**Pull request by mikelodder7**
This adds the first two functions across the FFI boundary and includes the .h header file.

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
Are the two `Cargo.lock` files intentional?

implementations/rust/Cargo.lock
implementations/rust/vault/Cargo.lock

**Comment by mikelodder7** [comment]
Next PR for me is to reconcile it down to just one at the rust folder level

**Comment by mrinalwadhwa** [comment]
cool, merging this.

**Comment by mikelodder7** [comment]
Next PR will delete 

implementations/rust/vault/Cargo.lock

I want to make sure it can go and not come back

**Pull request merged**
