### PR TITLE
feat(rust): upgrade heapless to v0.7.1 in signature_core

### PR DESCRIPTION
**Pull request by jared-s**
Heya @psinghal20!

 I've branched your fork in order to rebase from develop, kick the CI jobs off, and do some final checks.

I think the develop rebase may take case of the xx unused variable. We will see in a bit.

### CODE REVIEW

**Comment by jared-s** [comment]
Hey @mrinalwadhwa,

A dependency of ours, `heapless` has now begun to use a new stable feature in Rust 1.51. It looks like the builder images in CI are still using Rust 1.49. I PR'd a new Dockerfile that updates the builder images, but I think I need your help to push them to the image repo.

**Comment by mrinalwadhwa** [comment]
I can update the image, which PR?
>  I PR'd a new Dockerfile that updates the builder images

**Comment by jared-s** [comment]
> I can update the image, which PR?
> 
> > I PR'd a new Dockerfile that updates the builder images

I just landed it on develop: https://github.com/ockam-network/ockam/pull/1429

**Comment by mrinalwadhwa** [comment]
Got it, building the image now 👍

**Comment by jared-s** [comment]
Thanks @mrinalwadhwa ! As soon as that is pushed up, I'll restart the jobs. Looks like the published image is still at `d70b384ff4d40e403f9b5b171eada3ed6746117a9267e98ae530336747895fe2`

**Comment by jared-s** [comment]
Confirmed `cbda96698696625b29da843da8c7d1b37b775d5767d14bbf0f8233174735dca8` is now out there with 1.51. Thank you!

**Comment by mrinalwadhwa** [comment]
Just pushed the new image.

**Comment by jared-s** [comment]
Reopening didn't work. Going to try a new PR, possibly new branch.

**Pull request closed without merging**
