### PR TITLE
ci: parallelize

### PR DESCRIPTION
**Pull request by mrinalwadhwa**

### CODE REVIEW

**Comment by thomcc** [comment]
I'm not familiar enough with gradle to know exactly what this does, but is this attempting to parallelize cargo invocations?

If so, it's perhaps worth noting that running multiple invocations of cargo at the same time won't help — for one, cargo is already running many invocations of rustc in parallel, but for another, all but the first invocation will wait for it to finish before running (with a message like "Waiting for target directory lock" or similar — you may have seen it before)

**Comment by mrinalwadhwa** [comment]
The breakdown of gradle tasks is so CI can run them in parallel (in different runners / VMs).

We're down to ~7 minutes for the longest running actions (with cache hit) and ~16 minutes (with cache miss)

```
» gh pr checks
All checks were successful
0 failing, 56 successful, 0 skipped, and 0 pending checks

✓  All - Build                                          4m21s  https://github.com/ockam-network/ockam/runs/4664628556?check_suite_focus=true
✓  All - Build                                          4m24s  https://github.com/ockam-network/ockam/runs/4664628928?check_suite_focus=true
✓  All - List Gradle Tasks (macos-10.15, 11)            36s    https://github.com/ockam-network/ockam/runs/4664628736?check_suite_focus=true
✓  All - List Gradle Tasks (macos-10.15, 11)            3m18s  https://github.com/ockam-network/ockam/runs/4664629124?check_suite_focus=true
✓  All - List Gradle Tasks (macos-10.15, 16)            43s    https://github.com/ockam-network/ockam/runs/4664628751?check_suite_focus=true
✓  All - List Gradle Tasks (macos-10.15, 16)            40s    https://github.com/ockam-network/ockam/runs/4664629140?check_suite_focus=true
✓  All - List Gradle Tasks (macos-10.15, 17)            34s    https://github.com/ockam-network/ockam/runs/4664628768?check_suite_focus=true
✓  All - List Gradle Tasks (macos-10.15, 17)            33s    https://github.com/ockam-network/ockam/runs/4664629159?check_suite_focus=true
✓  All - List Gradle Tasks (macos-10.15, 8)             31s    https://github.com/ockam-network/ockam/runs/4664628708?check_suite_focus=true
✓  All - List Gradle Tasks (macos-10.15, 8)             34s    https://github.com/ockam-network/ockam/runs/4664629110?check_suite_focus=true
✓  All - List Gradle Tasks (ubuntu-20.04, 11)           35s    https://github.com/ockam-network/ockam/runs/4664628656?check_suite_focus=true
✓  All - List Gradle Tasks (ubuntu-20.04, 11)           23s    https://github.com/ockam-network/ockam/runs/4664629047?check_suite_focus=true
✓  All - List Gradle Tasks (ubuntu-20.04, 16)           28s    https://github.com/ockam-network/ockam/runs/4664628671?check_suite_focus=true
✓  All - List Gradle Tasks (ubuntu-20.04, 16)           25s    https://github.com/ockam-network/ockam/runs/4664629067?check_suite_focus=true
✓  All - List Gradle Tasks (ubuntu-20.04, 17)           23s    https://github.com/ockam-network/ockam/runs/4664628689?check_suite_focus=true
✓  All - List Gradle Tasks (ubuntu-20.04, 17)           39s    https://github.com/ockam-network/ockam/runs/4664629097?check_suite_focus=true
✓  All - List Gradle Tasks (ubuntu-20.04, 8)            24s    https://github.com/ockam-network/ockam/runs/4664628634?check_suite_focus=true
✓  All - List Gradle Tasks (ubuntu-20.04, 8)            39s    https://github.com/ockam-network/ockam/runs/4664629029?check_suite_focus=true
✓  All - List Gradle Tasks (windows-2019, 11)           4m9s   https://github.com/ockam-network/ockam/runs/4664628801?check_suite_focus=true
✓  All - List Gradle Tasks (windows-2019, 11)           4m15s  https://github.com/ockam-network/ockam/runs/4664629195?check_suite_focus=true
✓  All - List Gradle Tasks (windows-2019, 16)           4m22s  https://github.com/ockam-network/ockam/runs/4664628818?check_suite_focus=true
✓  All - List Gradle Tasks (windows-2019, 16)           4m22s  https://github.com/ockam-network/ockam/runs/4664629217?check_suite_focus=true
✓  All - List Gradle Tasks (windows-2019, 17)           4m12s  https://github.com/ockam-network/ockam/runs/4664628834?check_suite_focus=true
✓  All - List Gradle Tasks (windows-2019, 17)           4m28s  https://github.com/ockam-network/ockam/runs/4664629231?check_suite_focus=true
✓  All - List Gradle Tasks (windows-2019, 8)            4m16s  https://github.com/ockam-network/ockam/runs/4664628787?check_suite_focus=true
✓  All - List Gradle Tasks (windows-2019, 8)            4m16s  https://github.com/ockam-network/ockam/runs/4664629182?check_suite_focus=true
✓  Commits - Check                                      22s    https://github.com/ockam-network/ockam/runs/4664628505?check_suite_focus=true
✓  Commits - Check                                      19s    https://github.com/ockam-network/ockam/runs/4664628919?check_suite_focus=true
✓  Documentation - Check Examples                       3m58s  https://github.com/ockam-network/ockam/runs/4664628927?check_suite_focus=true
✓  Documentation - Check Examples                       3m35s  https://github.com/ockam-network/ockam/runs/4664668012?check_suite_focus=true
✓  Editorconfig - Lint                                  11s    https://github.com/ockam-network/ockam/runs/4664628509?check_suite_focus=true
✓  Editorconfig - Lint                                  10s    https://github.com/ockam-network/ockam/runs/4664628882?check_suite_focus=true
✓  Elixir - Build                                       4m35s  https://github.com/ockam-network/ockam/runs/4664628665?check_suite_focus=true
✓  Elixir - Build                                       5m13s  https://github.com/ockam-network/ockam/runs/4664628865?check_suite_focus=true
✓  Elixir - Lint                                        4m27s  https://github.com/ockam-network/ockam/runs/4664628553?check_suite_focus=true
✓  Elixir - Lint                                        5m47s  https://github.com/ockam-network/ockam/runs/4664629012?check_suite_focus=true
✓  Elixir - Test                                        5m10s  https://github.com/ockam-network/ockam/runs/4664628637?check_suite_focus=true
✓  Elixir - Test                                        6m20s  https://github.com/ockam-network/ockam/runs/4664629113?check_suite_focus=true
✓  Rust - Build                                         2m20s  https://github.com/ockam-network/ockam/runs/4664628782?check_suite_focus=true
✓  Rust - Build                                         1m51s  https://github.com/ockam-network/ockam/runs/4664629208?check_suite_focus=true
✓  Rust - Build Documentation                           2m36s  https://github.com/ockam-network/ockam/runs/4664628672?check_suite_focus=true
✓  Rust - Build Documentation                           1m56s  https://github.com/ockam-network/ockam/runs/4664629317?check_suite_focus=true
✓  Rust - Build Examples                                4m14s  https://github.com/ockam-network/ockam/runs/4664628856?check_suite_focus=true
✓  Rust - Build Examples                                3m10s  https://github.com/ockam-network/ockam/runs/4664629451?check_suite_focus=true
✓  Rust - Check Cargo Update                            1m32s  https://github.com/ockam-network/ockam/runs/4664628719?check_suite_focus=true
✓  Rust - Check Cargo Update                            1m36s  https://github.com/ockam-network/ockam/runs/4664629546?check_suite_focus=true
✓  Rust - Check Features - no_std alloc software_vault  1m25s  https://github.com/ockam-network/ockam/runs/4664629009?check_suite_focus=true
✓  Rust - Check Features - no_std alloc software_vault  1m24s  https://github.com/ockam-network/ockam/runs/4664629600?check_suite_focus=true
✓  Rust - Lint Formatting                               1m51s  https://github.com/ockam-network/ockam/runs/4664629066?check_suite_focus=true
✓  Rust - Lint Formatting                               1m43s  https://github.com/ockam-network/ockam/runs/4664629139?check_suite_focus=true
✓  Rust - Lint with Cargo Clippy                        1m44s  https://github.com/ockam-network/ockam/runs/4664628555?check_suite_focus=true
✓  Rust - Lint with Cargo Clippy                        1m41s  https://github.com/ockam-network/ockam/runs/4664628880?check_suite_focus=true
✓  Rust - Lint with Cargo Deny                          7m57s  https://github.com/ockam-network/ockam/runs/4664628639?check_suite_focus=true
✓  Rust - Lint with Cargo Deny                          6m47s  https://github.com/ockam-network/ockam/runs/4664629015?check_suite_focus=true
✓  Rust - Test                                          6m32s  https://github.com/ockam-network/ockam/runs/4664629187?check_suite_focus=true
✓  Rust - Test                                          6m42s  https://github.com/ockam-network/ockam/runs/4664629660?check_suite_focus=true
```

**Comment by mrinalwadhwa** [comment]
Tomorrow, I plan on trying your suggestion from https://github.com/ockam-network/ockam/issues/2342 of deleting our crates from `./target/debug/deps` and `target/debug/.fingerprint` before caching.

**Comment by thomcc** [comment]
Thanks, that clears it up for me.

**Pull request merged**
